### ISSUE TITLE
Code fails when there are no faces in the image

### ISSUE THREAD

**Issue by jaarac** [akofman/wider-face-pascal-voc-annotations#4]
0_Parade_Parade_0_452.jpg => ./WIDER_train_annotations/0_Parade_Parade_0_452.xml
Traceback (most recent call last):
  File "convert.py", line 86, in <module>
    convertWFAnnotations(ARGS['annotations_path'], ARGS['target_path'], ARGS['images_path'])
  File "convert.py", line 55, in convertWFAnnotations
    folder, basename, path, width, height = parseImFilename(imFilename, imPath)
  File "convert.py", line 41, in parseImFilename
    im = Image.open(os.path.join(imPath, imFilename))
  File "/home/cp2016/cp201613/epp/venv/lib/python3.8/site-packages/PIL/Image.py", line 2843, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './WIDER_train/images/0 0 0 0 0 0 0 0 0 0'

**Comment by pl-ang** [comment]
replace this while i < int(nbBndboxes) or i == 0: in line 60

**Comment by lowlevel-1989** [comment]
fix: https://github.com/akofman/wider-face-pascal-voc-annotations/pull/7
